#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

IFS='\n'
arr=($(git diff-tree --name-only --no-commit-id HEAD))
unset IFS
echo "Checking for any docker-compose files that are being committed..."
for x in $arr; 
do 
if [[ "$x" == *"docker-compose"* ]]; then
    echo "Testing compose file named: $x"
    test=`docker-compose -f $x config`
	return=`echo $?`
	if [ "$return" -eq "1" ]; then
	  echo "$x does not pass docker-compose config check"
	  echo "Not commiting..."
	  exit 1
	fi
   fi;
done;

# If you want to allow non-ASCII filenames set this variable to true.
#allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
#exec 1>&2

#exec docker-compose
