#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

exec  git diff-tree --name-only HEAD

# If you want to allow non-ASCII filenames set this variable to true.
#allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
#exec 1>&2

#exec docker-compose
