---
version: '3.6'

services:
  docksockprox:
    image: devinsmith/docksockprox:latest
    environment:
      - AUTH=1
      - BUILD=1
      - COMMIT=1
      - CONFIGS=1
      - CONTAINERS=1
      - DISTRIBUTION=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PLUGINS=1
      - POST=1
      - SERVICES=1
      - SESSION=1
      - SWARM=1
      - SECRETS=1
      - SYSTEM=1
      - TASKS=1
      - VOLUMES=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 2375
        published: 2375
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: any